## Numpy Operations 

In [2]:
import numpy as np

In [6]:
arr = np.arange(10)
print("Array Slicing : ",arr[2:7])
print("With steps : ",arr[1:8:2])
print("Negative Indexing : ",arr[-6])

Array Slicing :  [2 3 4 5 6]
With steps :  [1 3 5 7]
Negative Indexing :  4


In [ ]:
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
print("Specific Element : ",arr_2d[1,0]) # [1,0] means 1 columns 0th element. 
print("Entire Row : ",arr_2d[1]) # [1] means retrive the 1 row.
print("Entire column : ",arr_2d[:,1]) # [:,1] means retrive the 1 column.




Specific Element :  4
Entire Row :  [4 5 6]
Entire column :  [2 5 8]


## Sorting Operations

In [ ]:
Unsorted = np.array([1,9,8,6,5,4,3,2])
print("Sorted Array :",np.sort(Unsorted))

arr_2d_unsorted = np.array([[3,2,1],[1,3,2],[2,1,3]])
# axis = 0 means sorts the elements by columnwise.
print("Sorted 2d array by column : \n",np.sort(arr_2d_unsorted,axis=0))
# axis = 1 means sorts the elements by rowwise. 
print("Sorted 2d array by row : \n",np.sort(arr_2d_unsorted,axis=1))

Sorted Array : [1 2 3 4 5 6 8 9]
Sorted 2d array by column : 
 [[1 1 1]
 [2 2 2]
 [3 3 3]]
Sorted 2d array by row : 
 [[1 2 3]
 [1 2 3]
 [1 2 3]]


## Filtering the array

In [13]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
even = numbers[numbers % 2 == 0]
print("Even Numbers : " ,even)

Even Numbers :  [ 2  4  6  8 10]


## Filtering with mask 

In [14]:
mask = numbers > 5
print("Numbers greater than 5 :",numbers[mask])

Numbers greater than 5 : [ 6  7  8  9 10]


## Fancy indexing vs np.where()

In [15]:
indices = [0,2,4]
print(numbers[indices])

where_result = np.where(numbers > 5)
print("NP where function : ",numbers[where_result])

[1 3 5]
NP where function :  [ 6  7  8  9 10]


In [19]:
conditional_array = np.where(numbers > 5 , "true" , "false")
print(conditional_array)
 
# if(numbers > 5 )
#         true
# else 
#         false


['false' 'false' 'false' 'false' 'false' 'true' 'true' 'true' 'true'
 'true']


## Adding and Removing data

In [ ]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

combined = arr1 + arr2  # this adds both arrays 
print(combined)
combines = np.concatenate((arr1,arr2)) # this concatenate both arrays 
print(combines)

[5 7 9]
[1 2 3 4 5 6]


## Array Compatability 

In [24]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])
print("Compatability Shapes",a.shape == b.shape)

Compatability Shapes True


In [ ]:
Original = np.array([[1,2], [3,4] , [9,10]])
new_row = np.array([[5,6]])

with_new_row = np.vstack((Original,new_row)) # vstack function adds new row
print(Original)
print(with_new_row)

new_col = np.array([[7],[8],[11]])
with_new_col = np.hstack((Original,new_col)) # hstack function adds new columns 
print(with_new_col)

[[ 1  2]
 [ 3  4]
 [ 9 10]]
[[ 1  2]
 [ 3  4]
 [ 9 10]
 [ 5  6]]
[[ 1  2  7]
 [ 3  4  8]
 [ 9 10 11]]


In [4]:
arr = np.array([1,2,3,4,5])
deleted = np.delete(arr,2)
print("Array after deleting :",deleted)

Array after deleting : [1 2 4 5]
