## Numpy array and basics


In [2]:
import numpy as np

### Creating array using list

In [16]:
arr_1d = np.array([1,2,3])
print(arr_1d)
arr_2d = np.array([[1,2,3],[4,5,6]])
print(arr_2d)

[1 2 3]
[[1 2 3]
 [4 5 6]]


### Numpy vs List

In [12]:
l1 = [1,2,3]
print("List Multiplication :",l1 * 2)

arr = np.array([4,5,6])
print("Array Multiplication :",arr * 2)

import time
start = time.time()
l1 = [i*2 for i in range(1000000)]
print("\n List operation time : ", time.time() - start)

start = time.time()
arr = np.arange(1000000) * 2 # arange is the function is used to generate evenly spaced values within a given range.
print("\n Numpy operation time : ", time.time() - start)

arr = np.arange(50)
print(arr)





List Multiplication : [1, 2, 3, 1, 2, 3]
Array Multiplication : [ 8 10 12]

 List operation time :  0.022588014602661133

 Numpy operation time :  0.0015430450439453125
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]


### Creating array from scratch 

In [24]:
zeros = np.zeros((2,3))
print("Zeros Array :\n",zeros)

ones = np.ones((2,3))
print("Ones Array :\n",ones)

full = np.full((2,3),5)
print("full Array :\n",full)

random = np.random.random((2,3))
print("Random Array :\n",random)

sequence = np.arange(0,10,2)
print("Sequence Array :\n",sequence)


Zeros Array :
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones Array :
 [[1. 1. 1.]
 [1. 1. 1.]]
full Array :
 [[5 5 5]
 [5 5 5]]
Random Array :
 [[0.34983978 0.96296217 0.29775123]
 [0.90104105 0.42631297 0.0508989 ]]
Sequence Array :
 [0 2 4 6 8]


### Vector, Matrix and Tensor

In [36]:
vector = np.array([1,2,3])
print("Vector :",vector)

matrix = np.array([[1,2,3],
                   [4,5,6]])
print("Matrix :\n",matrix)

# when the dimensions increses then we called it as multidimensional array or tensor 
tensor = np.array([[[1,2],[3,4]],
                   [[5,6],[7,8]]]) 
print("Tensor :\n",tensor)
print("Dimensions :\n",tensor.ndim)




Vector : [1 2 3]
Matrix :
 [[1 2 3]
 [4 5 6]]
Tensor :
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Dimensions :
 3


### Array Properties 

In [ ]:
arr = np.array([[1,2,3],
                [4,5,6]])
print("Shape :",arr.shape) # No of rows and columns here (2,3)
print("Ndim :",arr.ndim) # returns the dimensions of array here (2)
print("Size :",arr.size) # returns the total no of elements in the array here (6)
print("Dtype :",arr.dtype) # returns the datatype of an array here (int64)

Shape : (2, 3)
Ndim : 2
Size : 6
Dtype : int64


### Array Reshaping

In [38]:
arr = np.arange(12)
print("Original Array \n", arr)
reshaped = arr.reshape(3,4)
print("Reshaped Array \n",reshaped)
flattened = arr.flatten()
print("Flattened Array \n",flattened)
# (returns view means original, instead of copy)
raveled = reshaped.ravel()
print("Raveled Array \n",raveled)
# Converts the matrices rows into columns (2x3) will converted to (3x2)
transpose = reshaped.T
print("transpose Array \n",transpose)




Original Array 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped Array 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened Array 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Raveled Array 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
transpose Array 
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
